### ISSUE TITLE
What kind of GPUs are needed?

### ISSUE THREAD

**Issue by hlyf-xs** [JJGO/UniverSeg#12]
Hi, This is a good job! But I want to know what kind of GPUs are needed.

**Comment by JJGO** [comment]
It really depends on the use case as well as the number of examples in the support size.

- For inference, we have successfully run UniverSeg on Nvidia V100, T4 and Titan Xp cards. 

- For most training runs we used Nvidia V100 cards with 32GB due to the increased GPU memory requirements of having 64 support set examples.
