### ISSUE TITLE
[Question] Data Preprocessing Protocol - Mid slice, axes extraction, and aspect ratio change for training and evaluation

### ISSUE THREAD

**Issue by xk-huang** [JJGO/UniverSeg#28]
Thanks for open-sourcing the code!
 
I am trying the reimplement UniverSeg but I have some questions about data preprocessing.
 
1) Mid slice 
 
In the supp., I found that only `mid-slices` are used for training and evaluation. But I found that in some datasets (e.g., BTCV), the mid slice is not optimal as it misses some other organs.
 
Here is an example of `mid slice` vs. its `latter slice`:
 
![mid-slice](https://github.com/JJGO/UniverSeg/assets/33593707/bfe256cd-f0f8-4d18-8a89-1675ba6b3e1c)
 
![latter-slice](https://github.com/JJGO/UniverSeg/assets/33593707/5b870d95-9dc1-49df-bcbe-0053d2f87893)
 
I am wondering how this protocol choice would affect the evaluation?
 
2) Three axis extraction
 
In the paper, all mid slices from the 3 axes are extracted for training and evaluation.
But some slices from `x-z` and `y-z` planes could be distorted. Do you still compute the metrics on them?
 
Still some samples of mid slices for `x-z` and `y-z` planes from BTCV:
 
![`x-z` and `y-z` planes](https://github.com/JJGO/UniverSeg/assets/33593707/515ce160-8c96-4fd6-903b-3a616bc92eb7)
 
3) Aspect ratio change
Specifically, the resolution of BTCV is (512,512,147), which means the `x-z` or `y-z` plane images are resized from (512,147) to (128, 128).
It raises another question that how the resize distortion affect the final performance.
 
 
 
Thanks in advance for your time and reply!

**Comment by VictorButoi** [comment]
Greetings! To provide answers to your three questions:

1. It's true that the midslice of the volume could potentially miss some organs, and that perhaps one could consider evaluating on all slices of the 3D volume. We only chose to do midslices because we didn't want to bias our evaluation.

2. This comes down to an issue in voxel-scaling of the original NIFTI files. We resample the NIFTIs using their header information so that everything is (1,1,1) for both the image and label volume.

3. Before we resize our image/volumes, we first pad them to be square to avoid distortions. Thus, for your BTCV example, first we would pad the volume to be (512,512,512) and then resize to (128,128,128).

**Comment by xk-huang** [comment]
Thanks again for the speedy reply!
