### ISSUE TITLE
Dataset and training codes release

### ISSUE THREAD

**Issue by CSCYQJ** [JJGO/UniverSeg#3]
It's a great work for the few-shot medical image segmentation problem! And I'd like to know whether the prepocessed dataset (or tasks) and the training codes will be released in the near future.

**Comment by JJGO** [comment]
Due to data user agreements, we cannot re-release other people datasets without their consent. Moreover, many of the datasets require that the user agrees to specific conditions first. Nevertheless, you can find the datasets we used in MegaMedical in Table3 of Appendix A.

Our training code is fairly standard and should be easy to reproduce, we will study releasing it. Appendix B includes additional implementation details to help with this.

**Comment by adalca** [comment]
I'll just add that there are *some* datasets you can download and try. 
See https://github.com/adalca/medical-datasets/blob/master/neurite-oasis.md for example for brains --- which includes a mid-slice selection. You'll need to do some minimal processing (resize to 128x128 and extract a label of interest) but it should be fairly quick to do!

**Comment by adalca** [comment]
Update: @CSCYQJ we have now added an example of downloading and using neurite-oasis in the tutorial (at the bottom, current section 8). See https://universeg.csail.mit.edu.
