### ISSUE TITLE
ensemble when inference?

### ISSUE THREAD

**Issue by bio-mlhui** [JJGO/UniverSeg#33]
Section 3.3 says that your final mask is the ensemble of multiple episodes. I think for few-shot learning, the core thing is using less training annotations to generalize well. Instead of averaging the dice score of each inference episode,  you directly ensemble difference episodes mask predictions into one. I think this is not consistent with few-shot inference

**Comment by VictorButoi** [comment]
With respect to our ensemble section, we do indeed consider the possibility of ensembling multiple probability maps derived from different support sets. Additionally, I agree with you that for few-shot learning* that one might not have so many labels to draw from; however, UniverSeg is not a few-shot learner, but rather an in-context one (we emphasize this in our paper). The comparison with other few-shot baselines (which we tune for comparison) is due to the lack of pre-existing works which consider scenarios where the numbers of labels isn't the biggest issue, but rather the necessity to train at all.
